version: 1.1a
backpackMaterial: CHEST
backpackName: "§eBackpack"
backpackLore: "§d§oRight click in hand to open."
backpackRecipe:
  shape:
    top: "LGL"
    middle: "LCL"
    bottom: "LGL"
  materials:
    L: "LEATHER"
    G: "GOLD_INGOT"
    C: "CHEST"