name: Backpacks
author: Yellow571
version: 1.1af2
api-version: "1.15"
main: ml.yellowmc.backpacks.Main

commands:
  backpacks:
    description: Parent command for Backpacks.
    usage: /backpacks <subcommand> <args>
    aliases: [bp]

permissions:
  backpacks.*:
    description: Allows full control over backpacks.
    default: op
    children:
      backpacks.give: true
      backpacks.craft: true
      backpacks.use: true
      backpacks.modify: true
  backpacks.give:
    description: Allows usage of /givebackpack.
    default: op
  backpacks.craft:
    description: Allows crafting of backpacks.
    default: op
  backpacks.use:
    description: Allows usage of backpacks.
    default: true
  backpacks.modify:
    description: Allows modification of the backpack.
    default: op